### ISSUE TITLE
PDF/A-2 6.7.4

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#763] opened 2017-06-04 07:39 UTC
veraPDF 1.4.7 does not validate Lang entries according to ISO 19005-2:2011, clause 6.7.4.
Here are some test cases:

[6.7.4-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1050173/6.7.4-fail-1.pdf)
[6.7.4-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1050174/6.7.4-fail-2.pdf)
[6.7.4-fail-3.pdf](https://github.com/veraPDF/veraPDF-library/files/1050175/6.7.4-fail-3.pdf)
[6.7.4-pass-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1050179/6.7.4-pass-1.pdf)

(I do not yet have a test case for Lang in a structure element dictionary.)

**Comment by bdoubrov** [comment] 2017-06-08 08:22
Thanks for reporting this issue. Indeed, veraPDF does not verify the correctness of /Lang value. We'll try to add this check in the next release

**Comment by BezrukovM** [comment] 2017-07-13 08:32
CosLang type and its links has been added in pdf model and model implementation already. All that left is to add that rule into validation profiles.

**Comment by bdoubrov** [comment] 2017-07-29 05:47
The issue is fixed in version 1.7.94

Note that the test files 6.7.4-fail-2.pdf and 6.7.4-fail-3.pdf are not fully correct, as they use a custom tag instead of the the /Span tag to define Lang for the marked content sequence

**Closed by bdoubrov** 2017-07-29 05:47 UTC
Labels: in progress

**Comment by a20god** [comment] 2017-07-29 09:19
Well, unlike PDF/UA, PDF/A doesn't require the language to be specified (it's a should, not a shall). It only requires the Lang entry in a property list (and elsewhere) to have a value as specified by ISO 32000-1. If the marked-content tag is Span or not does not matter (IMHO). The custom tag used in 6.7.3-fail-2.pdf is just a marked-content tag, not a structure tag. As far as I can tell, PDF/A does not restrict the tags of marked-content sequences.

**Comment by a20god** [comment] 2017-08-18 12:22
Are you sure this is fixed? veraPDF 1.9.14 claims that these documents are compliant:
[6.8.4-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1234387/6.8.4-fail-1.pdf) (PDF/A-1)
[6.7.4-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1234389/6.7.4-fail-1.pdf) (PDF/A-2)
