### ISSUE TITLE
preflight passes, veraPDF shows clause="6.2.11.4" error

### ISSUE THREAD

**Issue by kernie** [veraPDF/veraPDF-library#1019] opened 2019-03-24 17:38 UTC
Hi,

I generated a PDF with lualatex and checked it with Preflight for pdf/a-2b compliance with no error.

Checking with veraPDF fails with 
```
      <validationReport profileName="PDF/A-2B validation profile" statement="PDF file is not compliant with Validation Profile requirements." isCompliant="false">
        <details passedRules="120" failedRules="1" passedChecks="824" failedChecks="1">
          <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="4" status="failed" passedChecks="0" failedChecks="1">
            <description>If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program,&#xa;			regardless of whether a CID in the font is referenced or used by the PDF or not.</description>
            <object>PDCIDFont</object>
            <test>fontFile_size == 0 || fontName.search(/[A-Z]{6}\+/) != 0 || CIDSet_size == 0 || cidSetListsAllGlyphs == true</test>
            <check status="failed">
              <context>root/document[0]/pages[0](4 0 obj PDPage)/contentStream[0](7 0 obj PDContentStream)/operators[13]/font[0](AZVWNA+TeXGyreTermes-Regular)/DescendantFonts[0](AZVWNA+TeXGyreTermes-Regular)</context>
            </check>
          </rule>
        </details>
      </validationReport>
```

Is this a bug?

Thanks,
Maarten

veraPDF version
```
<buildInformation>
    <releaseDetails id="core" version="1.12.1" buildDate="2018-05-08T18:57:00+02:00"></releaseDetails>
    <releaseDetails id="validation-model" version="1.12.1" buildDate="2018-05-08T20:39:00+02:00"></releaseDetails>
    <releaseDetails id="gui" version="1.12.1" buildDate="2018-05-08T22:06:00+02:00"></releaseDetails>
  </buildInformation>
```
[pdfa2btest.pdf](https://github.com/veraPDF/veraPDF-library/files/3000633/pdfa2btest.pdf)
:

**Comment by bdoubrov** [comment] 2019-03-26 06:04
The issue is related to the fact that the CIDSet value of the embedded font does not include the bit for the glyph with CID=0 (.notdef). Apparently, this bit is not required as any embedded font is required to contain this glyph. So, I do confirm this is a veraPDF issue, which will be fixed now in the dev version and will be included into the planned 1.14 release.

**Closed** 2019-03-26 08:44 UTC
Labels: P2, bug
