### ISSUE TITLE
Validation errors visualization (or some font validation bug)

### ISSUE THREAD

**Issue by LSinev** [veraPDF/veraPDF-library#969] opened 2018-05-21 18:26 UTC
## Dev Effort
5D

## Description
[xcharter-doc-pdfa1b.pdf](https://github.com/veraPDF/veraPDF-library/files/2023643/xcharter-doc-pdfa1b.pdf)
[xcharter-doc-pdfa1b_a1b.zip](https://github.com/veraPDF/veraPDF-library/files/2023652/xcharter-doc-pdfa1b_a1b.zip)

File tested and validation results attached. Both in Adobe Preflight and 3-Heights PDF Validator validated with no errors. But with veraPDF 1.12.1 and 1.13.2 produces Glyph errors (ISO 19005-1:2005, Clause 6.3.5 and 6.3.6).
Is there a tool to visualize place of these glyph errors in PDF (even if this is a bug in veraPDF)?

**Comment by bdoubrov** [comment] 2018-05-21 18:46
Hi @LSinev , thanks for reporting the issue. Looks like indeed veraPDF can't properly parse XCharter fonts. 
 As for the visualization, the indication of the validation error is given by the path to the object that triggered this issue. Like, for example, this one:
> root/document[0]/pages[3](66 0 obj PDPage)/contentStream[0](67 0 obj PDContentStream)/operators[9]/usedGlyphs[0](WQGEMD+XCharterMathMI 73 0 0)

It means that the issue was caused by the glyph with character code 73 of the font WQGEMD+XCharterMathMI, which was the 0th glyph in the 9th operator on the 3rd page (all indexes are 0-based).

**Comment by a20god** [comment] 2018-05-23 11:31
I think the XCharter fonts are broken. Some charstrings start with a callsubr command and the first command in the subroutine is hsbw. However, the Type 1 Font Format specification says:

> Either sbw or hsbw must be used once as the first command in a character outline definition.

That is, the embedded Type 1 fonts do not conform to the Type 1 Font Format specification, therefore the PDF document does not conform to PDF Reference 1.4, therefore it doesn't conform to PDF/A-1b.

As the charstrings to not correctly specify the glyph widths, veraPDF may well complain about incorrect glyph widths.

**Comment by bdoubrov** [comment] 2018-12-04 07:16
We opened a new issue to investigate this Bitstream Charter case: https://github.com/veraPDF/veraPDF-library/issues/981

**Comment by carlwilson** [comment] 2019-08-22 10:18
@bdoubrov could you provide an update for this issue please.

**Comment by bdoubrov** [comment] 2019-08-22 12:09
I do confirm veraPDF has issues parsing the charstings of Type1 fonts, not starting with hsbw. Stricktly speaking, such charstings are invalid. Yet, I think, we can make our Type1 font parser more tolerant to such deviation from the standard and report it in the log as a PDF (or rather Type1 error) rather than a validation error. 

So, I suggest we fix this in the next release

**Comment by bdoubrov** [comment] 2022-01-24 11:30
Fix released in v1.20

**Closed by bdoubrov** 2022-01-24 11:30 UTC
Labels: feature, P2, fixed-in-dev
