### ISSUE TITLE
GreenField x PDFBox validation - Error in Greenfield

### ISSUE THREAD

**Issue by eugeniogz** [veraPDF/veraPDF-library#1252] opened 2022-05-22 11:20 UTC
If I validate a simple doc which uses one font and in sequence validate a second document with another embedded font the validation fails in Greenfield for the second file with the error:
"Glyph width information in the embedded font program is not consistent with the Widths entry of the font dictionary".

Using PDFBox validation the error didn't occurs.
if I change the structure of one of the two documents, adding a picture for example, the error didn't appears. 

Versions used 1.20.1 - java

**Comment by eugeniogz** [comment] 2022-05-22 11:38
If I validate a simple doc which uses one font and in sequence validate a second document with another embedded font the validation fails in Greenfield for the second file with the error:
"Glyph width information in the embedded font program is not consistent with the Widths entry of the font dictionary".

Using PDFBox validation the error didn't occurs.
if I change the structure of one of the two documents, adding a picture for example, the error didn't appears. 

Versions used 1.20.1

**Comment by bdoubrov** [comment] 2022-05-23 07:52
Hi @eugeniogz I wonder if you could attach the PDF files you mention in the issue?

**Comment by eugeniogz** [comment] 2022-05-26 00:26
reopened aftter testing again with the files above

**Comment by bdoubrov** [comment] 2022-05-27 09:42
@eugeniogz we are not able to reproduce the issue. If I use either CLI or the desktop version of veraPDF 1.20.1 greenfield and perform validation of the two attached files in any order any number of times they still remain valid. Would you please further clarify your test scenario:
- how exactly do you perform validation of these two files one after another? If you use CLI, please provide all CLI arguments. If you use Java code, it would be great to see the code sample
- please provide also the details for your local environment: Java version, OS

**Comment by eugeniogz** [comment] 2022-05-28 15:49
The validation is done using a java program.
Operating system: Ubuntu 20.04.1
Java: openjdk version "1.8.0_312"

Java code:

public static void main(String args[]) throws IOException {
App a1 = new App();
System.out.println("PDF A "+ a1.checkPdfVera(
"out/quick_brown_fox_PDFA-2b-FreeSans.pdf", "2b"));
System.out.println("PDF A "+ a1.checkPdfVera(
"out/quick_brown_fox_PDFA-2b-Karla.pdf", "2b"));
}

public String checkPdfVera(String file, String flavorString) throws
FileNotFoundException {
//PdfBoxFoundryProvider.initialise();
VeraGreenfieldFoundryProvider.initialise();
try {
PDFAParser parser=null;
PDFAValidator validator=null;
if (flavorString != null) {
PDFAFlavour flavour = PDFAFlavour.fromString(flavorString);
parser = Foundries.defaultInstance().createParser(new File(file),
flavour);
validator = Foundries.defaultInstance().createValidator(flavour, false);
} else {
parser = Foundries.defaultInstance().createParser(new File(file));
validator = Foundries.defaultInstance().createValidator(parser.getFlavour(),
false);
}

ValidationResult result = validator.validate(parser);
return result.isCompliant()?parser.getFlavour().toString():"Not Ok";
} catch (Exception e) {
e.printStackTrace();
return "Not Valid";
}
}

**Comment by bdoubrov** [comment] 2022-05-30 11:05
The issue seems to be related to the PDFParser object that is not closed by the end of the document processing. As a result, its font cache is not cleaned. Here is an easy modification of the code that fixes this issue:

```
public String checkPdfVera(String file, String flavorString) {
   VeraGreenfieldFoundryProvider.initialise();
   PDFAFlavour flavour = flavorString != null ? PDFAFlavour.fromString(flavorString) : PDFAFlavour.NO_FLAVOUR;
   try (PDFAParser parser = Foundries.defaultInstance().createParser(new File(file), flavour);
       PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false)) {
       ValidationResult result = validator.validate(parser);
       return result.isCompliant() ? parser.getFlavour().toString() : "Not Ok";
   } catch (Exception e) {
      e.printStackTrace();
      return "Not Valid";
   }
}
```

We'll also add an automatic font cache clean up for any new PDF document opened in the parser. But it will be available only in the dev version till the next release.

**Closed by bdoubrov** 2022-05-30 11:05 UTC
