### ISSUE TITLE
Unable to execute XML-report, letters with ÅÄÖ in filename

### ISSUE THREAD

**Issue by maritbengtsson** [veraPDF/veraPDF-library#754] opened 2017-05-29 09:45 UTC
veraPDF version 1.4.6 GUI
OS windows 10
language swedish

**Comment by bdoubrov** [comment] 2017-06-09 10:13
Would you please clarify, whether 
- you can't select a file with these letters in the veraPDF GUI, 
- or you select the file and trigger the XML report generation, but the XML report is not generated,
- or the report is generated, but contains invalid/incomplete information?

**Comment by carlwilson** [comment] 2017-08-05 13:26
I've tried to reproduce this on a Windows 7 machine set to Swedish settings, I was able to do all of the above as well as save the XMl report to a name with a selection of these characters in it. Will test on a Windows 10 machine.

**Comment by carlwilson** [comment] 2022-02-01 13:38
@maritbengtsson we believe that this may have been fixed in the Windows C libraries. We will be testing it before the 1.22 release and closing this. It would be great if you could try this with a recent version of Windows and veraPDF to see if the issue still affects you?

**Comment by georgetarazevich** [comment] 2022-04-15 14:39
XML-report with letters ÅÄÖ in file name can be obtained using  veraPDF v. 1.21.121 

Checked on VM Windows 10,  Java v. 1.8, language Swedish
![XML-report with letters ÅÄÖ in filename](https://user-images.githubusercontent.com/12056147/163584111-399d184c-b77b-4528-b6bf-95c696a8b880.jpg)
.

**Comment by bdoubrov** [comment] 2022-04-21 12:23
Seems to be working fine with the latest stable release 1.20.1

**Closed by bdoubrov** 2022-04-21 12:23 UTC
Labels: P0
