### ISSUE TITLE
Invalid ID for PDF/A-1

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#887] opened 2017-08-10 08:06 UTC
veraPDF 1.7.37 throws an exception for this document:
[6.1.3-01-pass-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1214063/6.1.3-01-pass-2.pdf)
However, ISO 19005-1:2005 requires only the presence of ID, it does not state any requirements for the value.

**Comment by a20god** [comment] 2017-08-10 09:46
The document does not conform to Table 3.12 of PDF Reference 1.4, though.

**Comment by bdoubrov** [comment] 2017-08-16 13:34
I agree throwing an exception is probably too hard. We can log a warning that we see PDF 1.4 Reference violation, as we do it in other places. 

In fact, PDF/A-1 does have a requirement that IDs have the same value if they are both present in the first page tralier and the last trailer of the linearized PDF. Allowing arbitrary value of the ID key would mean requiring comparison ofarbitrary PDF objections. This is clearly not an intention. 

So, after the exception is fixed, we can mark this issue as a duplicate of  #827.

**Comment by a20god** [comment] 2017-08-16 13:38
My PDF/A validator compares arbitrary objects for ID (it had that code anyway, for comparing Separation arrays of the same name, for instance), but reports a PDF Reference 1.4 violation if ID is not an array of two strings. This doesn't affect the final outcome (pass or fail), it just results in different messages.

**Comment by shem-sergey** [comment] 2017-08-22 14:33
Closed in PR https://github.com/veraPDF/veraPDF-validation/pull/237.

**Closed by shem-sergey** 2017-08-22 14:33 UTC
Labels: in progress
