### ISSUE TITLE
ca/CA  not a number for 6.4 of PDF/A-1

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#898] opened 2017-08-17 08:01 UTC
In this document, ca in an ExtGState object is a name (1.0) rather than the number 1.0, but veraPDF 1.9.14 thinks the document conforms to ISO 19005-1:2005:
[6.4-05-fail-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1230515/6.4-05-fail-4.pdf)
At least, the document violates PDF Reference 1.4.

**Comment by bdoubrov** [comment] 2017-08-17 09:00
This is a duplicate of #827 

As full PDF 1.4 (or ISO 32000-1) validation is out of scope, at the moment veraPDF results for malformed documents are unpredictable. We are still discussing how to handle this other similar cases. But most likely we'll indeed report them as PDF syntax errors and document which exactly PDF syntax checks we implement.

Of course, any such syntax error would result in the PDF/A validation error as well.

**Closed** 2017-08-28 15:00 UTC
Labels: duplicate, in progress
