### ISSUE TITLE
veraPDF does not delete temporary files

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#882] opened 2017-08-09 14:00 UTC
The temporary files created by veraPDF (for concatenating the streams if the Contents entry of a page object is an array) are not deleted by veraPDF. They pile up until they are deleted by the operating system (if the operating system does that auomatically at all). If running veraPDF as, say, a web service, this could be a problem (DoS attack).

The temporary files may also leak confidential information.

**Comment by carlwilson** [comment] 2017-08-09 14:07
+1 for this, temp file management should be a priority for the next release, but it won't make 1.8 which will be out very shortly.

**Comment by a20god** [comment] 2017-08-09 14:18
Avoiding temporary files completely would be even better.

**Comment by shem-sergey** [comment] 2017-08-11 08:18
The big stream management improvement was done in https://github.com/veraPDF/veraPDF-parser/pull/286.
@a20god, please check the last version, it should not have issue with temp files.

**Comment by a20god** [comment] 2017-08-11 08:39
Temporary files are now deleted, but https://github.com/veraPDF/veraPDF-library/issues/883 is not fixed.

**Comment by ravn** [comment] 2017-08-11 09:12
@a20god  You need somewhere to store the bytes if you do not want the amount of RAM available to the JVM a limiting factor in scalability.

**Comment by a20god** [comment] 2017-08-11 09:59
Add a new type of stream (filter) which reads from the streams in an array, one by one, inserting a space character when switching from one stream to the next one.

**Comment by a20god** [comment] 2017-08-11 12:10
Disk space is also an issue:
[big.pdf](https://github.com/veraPDF/veraPDF-library/files/1217768/big.pdf)

**Comment by ravn** [comment] 2017-08-11 12:18
@a20god  I cannot open big.pdf.  Is it broken?

**Comment by a20god** [comment] 2017-08-11 12:20
Open with what? The concatenated content streams amount to  (IIRC) 32 GByte; uncompressing and scanning that takes some time...

**Comment by ravn** [comment] 2017-08-11 12:26
@a20god  Ah, a pathological example.  You could have mentioned that...  Sounds like a prime candidate for an integration test.

**Comment by a20god** [comment] 2017-08-11 12:32
I thought most of my sample documents were pathological ;-)

**Comment by ravn** [comment] 2017-08-14 13:31
It appears the culprit is that the veraPDF-parser class org.verapdf.io.InternalOutputStream has a helper method getInternalOutputStream which registers the file with `deleteOnExit()` which is consistent with the behavior you report.   As InternalOutputStream _has_ a close method it would be a simple change to have a boolean "deleteWhenClosing" passed in in a new constructor which is then dealt with in the close method instead of relying on the JVM doing the work at shut down time.

**Comment by BezrukovM** [comment] 2017-10-30 08:40
@a20god thank you for good example file for wrong concatenation logic (big.pdf).
1) Stream concatenation has been changed (for greenfield parser). Added a new stream class which reads from array of streams. Now we are not creating any new temp files for stream concatenation.
2) About `deleteOnExit`: I have checked all our code with creating temporary files. Almost all logic with them has been refactored. Files will be deleted when we do not need them (streams closing, etc.). And only if something goes wrong and file has not been deleted, we will mark it with `deleteOnExit`.
The last place where we are not deleting files manually and still using only `deleteOnExit` is xml and html reports in the GUI.

All these changes has been merged with https://github.com/veraPDF/veraPDF-parser/pull/319 PR and included into veraPDF 1.9.50 (GF version).

I think that I may close this issue. If something has been missed, feel free to reopen it.

**Closed by BezrukovM** 2017-10-30 08:40 UTC

**Comment by ravn** [comment] 2017-10-30 16:02
Thanks.

The current pom.xml in https://github.com/veraPDF/veraPDF-library/blob/integration/pom.xml reports   <version>1.9.0-SNAPSHOT</version>, which Maven thinks is older than 1.9.50.

What is the correct way to get the Maven artifacts corresponding to your fix?

**Comment by ravn** [comment] 2017-11-14 16:05
I have now tried with updating the 

I still have a proliferation of files in /tmp so it appears this bug is not fixed.  I pass in an inputstream (which is autoclosed) so it appears that this inputstream is saved to disk and it is those files that stay behind.  /proc/.../fd shows that these files are still open by the JVM.

I am using this maven pom.xml snippet
```
    <properties>
...
        <!-- releases at https://github.com/veraPDF/veraPDF-validation/releases -->
        <verapdf.validation.version>1.9.57</verapdf.validation.version>
    </properties>

    <!-- To get latest builds before they arrive on maven central. As the
    development team does not update the version in the public sources, we
    cannot build them ourselves.
    -->
    <!-- http://docs.verapdf.org/develop/ -->

    <repositories>
        <repository>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>vera-dev</id>
            <name>Vera development</name>
            <url>http://artifactory.openpreservation.org/artifactory/vera-dev</url>
        </repository>
    </repositories>

    <dependencies>
...
        <dependency>
            <groupId>org.verapdf</groupId>
            <artifactId>validation-model</artifactId>
            <version>${verapdf.validation.version}</version>
        </dependency>

```

The actual code doing work is:
```

        PDFAFlavour flavour = PDFAFlavour.byFlavourId(flavorId);
        PDFAValidator validator = Foundries.defaultInstance().createValidator(flavour, false);
        PDFAParser loader = Foundries.defaultInstance().createParser(inputStream, flavour);
        ValidationResult result = validator.validate(loader);

        // do in-memory generation of XML byte array - as we need to pass it to Fedora we need it to fit in memory anyway.

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        XmlSerialiser.toXml(result, baos, prettyXml, false);
        final byte[] byteArray = baos.toByteArray();
        return byteArray;
```

If the API has changed since I wrote this, I would appreciate a hint.

**Comment by BezrukovM** [comment] 2017-11-14 16:59
@ravn, 1) PDFAParser has to be closed (loader.close();).
2) what version of veraPDF dependancies do you using? I am talking about versions maven has downloaded for you. Can you check that this is a last version? I have made a big work with temp files logic not far ago.
3) I have checked all our code with creating temporary files (GF version). Every temp file has to be deleted on stream closing. If parser closing will not help, then we will have to investigate what streams are not closed properly.
if the problem will still reproduce after PDFAParser closing, let us know, please.
