### ISSUE TITLE
N in DestOutputProfile

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#764] opened 2017-06-04 14:23 UTC
Clause 6.2.3 of ISO 19005-2:2011 reads:
"...and a valid ICC profile stream as the value of its DestOutputProfile key"

The definition of ICC profile streams in ISO 32000-1:2008 8.6.5.5 requires the N key to match the number of components in the ICC profile.

veraPDF 1.4.7 fails to detect the violation of that requirement  in this document (N is 4 for an RGB ICC profile stream):
[RichardZ.pdf](https://github.com/veraPDF/veraPDF-library/files/1050393/RichardZ.pdf)

**Comment by bdoubrov** [comment] 2017-06-08 07:28
Asin case of https://github.com/veraPDF/veraPDF-library/issues/773, we consider this as a violation of ISO 32000-1, rather than PDF/A validation error. But as mentioned in https://github.com/veraPDF/veraPDF-library/issues/773, I'll double check this at the Validation Technical Working Group.

**Comment by a20god** [comment] 2017-06-08 08:29
As 6.2.3 explicitely requires a "valid ICC profile stream" veraPDF should validate against the definition of "valid ICC profile stream" in ISO 32000-1:2008 even though veraPDF usually doesn't check for violations of ISO 32000-1:2008 (as you stated in https://github.com/veraPDF/veraPDF-validation/issues/156).
Thanks for checking with the VTWG!

**Comment by bdoubrov** [comment] 2019-01-03 11:53
Duplicate of #773

**Closed by bdoubrov** 2019-01-03 11:53 UTC
Labels: duplicate, question
