### ISSUE TITLE
Adobe reports problem inside the Font, but verapdf says, that all is ok

### ISSUE THREAD

**Issue by LugPaj** [veraPDF/veraPDF-library#1410] opened 2024-02-15 09:21 UTC
Hello, 

Adobe reports a problem in the font, but verapdf claims, that all is ok. Is really all ok, or does verapdf don't check the font in the same manner as adobe uses it?

in my opinion PDF/A should garantee, that you have a reliable viewing experience. But here it didn't work. Or does Adobe have a bug here?

[S2_222_reduced_PDFA.pdf](https://github.com/veraPDF/veraPDF-library/files/14294046/S2_222_reduced_PDFA.pdf)

**Comment by bdoubrov** [comment] 2024-02-22 13:33
This is a duplicate of https://github.com/veraPDF/veraPDF-library/issues/811 . 

I also see no errors reported by Adobe Preflight (PDF/A-3b), Adobe Acrobat Pro, Continuous release. So, I think Adobe Acrobat Preflight and veraPDF both agree that the document is a valid PDF/A-3B.

**Closed** 2024-03-11 11:11 UTC
