### ISSUE TITLE
some error in validating

### ISSUE THREAD

**Issue by edrobal** [veraPDF/veraPDF-library#517] opened 2016-03-02 11:08 UTC
I'm testing a pdf library "gnupdf". It's a light library doing only what I need. But some features are not or badly implemented so I debug it and I try to use veraPDF for this and I receive only the message "some error in validating" and there is no report so it's not very useful.

**Comment by bdoubrov** [comment] 2016-03-03 10:27
Hi @edrobal,

I wonder if you can provide the input PDF file you are trying to validate? I still don't see any attachments to your message.

**Comment by edrobal** [comment] 2016-03-03 10:45
Hello.
May be your antimalware is removing attachment. I resend it.
Regards.

Le 03. 03. 16 11:27, Boris Doubrov a écrit :
>
> Hi @edrobal <https://github.com/edrobal>,
>
> I wonder if you can provide the input PDF file you are 
> trying to validate? I still don't see any attachments to 
> your message.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/517#issuecomment-191696527>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by bdoubrov** [comment] 2016-03-03 13:05
I'm sotty, but I still don't see any attached files. You can check this on on the github page of this issue:
https://github.com/veraPDF/veraPDF-library/issues/517

Would you try attaching file via the web interface?

**Comment by edrobal** [comment] 2016-03-03 13:37
[test.pdf](https://github.com/veraPDF/veraPDF-library/files/156826/test.pdf)

**Comment by bdoubrov** [comment] 2016-03-03 15:18
Well, in fact veraPDF can be used to identify the issues, but not explicitly. Here is the log you see if you run verapdf at your test file:

`Exception raised while validating C:\Users\Boris\Desktop\veraPDF\izPack\issue517-test.pdf`
`org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation`
`        at org.verapdf.pdfa.validators.BaseValidator.validate(BaseValidator.java:373)`
`        at org.verapdf.cli.VeraPdfCliProcessor.processStream(VeraPdfCliProcessor.java:134)`
`        at org.verapdf.cli.VeraPdfCliProcessor.processFile(VeraPdfCliProcessor.java:118)`
`        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:88)`
`        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:65)`
`Caused by: java.lang.ClassCastException: org.apache.pdfbox.cos.COSDictionary cannot be cast to org.apache.pdfbox.cos.COSStream`
`        at org.apache.pdfbox.pdmodel.graphics.pattern.PDTilingPattern.getContentStream(PDTilingPattern.java:172)`
`        ... 10 more`

The exception clearly says that there is a PDF syntax issue: the tiling pattern objecthas type Dictionary, while it is expected that it is of type Stream. And indeed if I open your test file in the text editor and search for the string "Pattern", I find the following PDF object:

`8 0 obj`
`<<`
`/Type /Pattern`
`/PatternType 1/PaintType 1/TilingType 1/BBox[0.0000 0.0000 57.0000 57.0000]/XStep 57/YStep 57/Resources<</ProcSet[/PDF/ImageC]/XObject<</Image1 6 0 R>>>>`
`>>`

It is exactly the one that causes issues. It is of type Dictionary, while Tiling patterns should be represented by Stream objects. See clause 8.7.3 "Tiling Patterns" from the PDF specification: [ISO 32000-1](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf)

**Comment by THausherr** [comment] 2016-03-03 19:16
fixed in https://issues.apache.org/jira/browse/PDFBOX-3259, now the method returns null.

**Comment by bdoubrov** [comment] 2016-04-06 12:11
Included into the release:

http://verapdf.org/2016/04/01/verapdf-0-12-released-alongside-first-version-of-wiki-validation-rules/

**Closed** 2016-04-28 08:54 UTC
