### ISSUE TITLE
SMask entry in XObject dictionary (PDF/A-1)

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#897] opened 2017-08-16 13:16 UTC
6.4 of ISO 19005-1:2005 (with TC2) says:

> An XObject dictionary shall not contain the SMask key.

Note that there is no wording restricting that rule to XObjects where SMask makes sense (images).

veraPDF 1.9.3 does not detect the violation of that clause in this document:
[6.4-01-fail-2.pdf](https://github.com/veraPDF/veraPDF-library/files/1228275/6.4-01-fail-2.pdf)

**Comment by bdoubrov** [comment] 2017-08-17 09:01
This is a duplicate of #827

**Comment by BezrukovM** [comment] 2017-11-16 11:52
All necessary changes in model and implementation has been done.
Validation profiles fixes are left

**Comment by BezrukovM** [comment] 2017-11-16 12:12
Fixed in veraPDF 1.9.70

**Closed by BezrukovM** 2017-11-16 12:13 UTC
Labels: duplicate, enhancement, in progress
