### ISSUE TITLE
Unsupported major.minor version

### ISSUE THREAD

**Issue by edrobal** [veraPDF/veraPDF-library#502] opened 2016-02-28 19:31 UTC
I install on linux with the latest sdk and I have this error message :
Unsupported major.minor version 51.0
Unable to test.

Regards.

**Comment by carlwilson** [comment] 2016-02-29 09:06
Hi @edrobal, I have a feeling that the problem is that you're running the code on an unsupported version number, we only support Java 7 onwards. Could you let us know what version you're running please, i.e.

    java -version

Thanks.

**Comment by edrobal** [comment] 2016-02-29 09:56
I use jdk 8. Why do not support it ? There is no problem 
with it.
Regards

Le 29. 02. 16 10:06, Carl Wilson a écrit :
>
> Hi @edrobal <https://github.com/edrobal>, I have a feeling 
> that the problem is that you're running the code on an 
> unsupported version number, we only support Java 7 
> onwards. Could you let us know what version you're running 
> please, i.e.
>
> |java -version
> |
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-190111892>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by carlwilson** [comment] 2016-02-29 20:07
Hi again, sorry for not responding sooner, we were putting together the new release today, the installer is [available here](http://downloads.verapdf.org/rel/verapdf-installer.zip). Could you give that a test and see whether your problem persists. If so then please you give me a little more information about your Java version and OS, e.g.

    verapdf cfw$ java -version
    java version "1.8.0_51"
    Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
    Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
    verapdf cfw$ 

The above is from my Mac mini test box and it has Java 8 installed and works with the latest version of the veraPDF installer, GUI and CLI.

**Comment by edrobal** [comment] 2016-03-01 12:32
I have the same error :
Unsupported major.minor version 51.0
I use : java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
My OS :
Linux hector 3.1.10-1.29-desktop #1 SMP PREEMPT Fri May 31 
20:10:04 UTC 2013 (2529847) x86_64 x86_64 x86_64 GNU/Linux
Regards

Le 29. 02. 16 21:07, Carl Wilson a écrit :
>
> Hi again, sorry for not responding sooner, we were putting 
> together the new release today, the installer is available 
> here 
> <http://downloads.verapdf.org/rel/verapdf-installer.zip>. 
> Could you give that a test and see whether your problem 
> persists. If so then please you give me a little more 
> information about your Java version and OS, e.g.
>
> |verapdf cfw$ java -version
> java version "1.8.0_51"
> Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
> Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
> verapdf cfw$
> |
>
> The above is from my Mac mini test box and it has Java 8 
> installed and works with the latest version of the veraPDF 
> installer, GUI and CLI.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-190360865>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by edrobal** [comment] 2016-03-01 15:13
I found the bug. The JDK_HOME path was openjdk path. I 
change it and now all is OK.
Thanks
Regards

Le 29. 02. 16 21:07, Carl Wilson a écrit :
>
> Hi again, sorry for not responding sooner, we were putting 
> together the new release today, the installer is available 
> here 
> <http://downloads.verapdf.org/rel/verapdf-installer.zip>. 
> Could you give that a test and see whether your problem 
> persists. If so then please you give me a little more 
> information about your Java version and OS, e.g.
>
> |verapdf cfw$ java -version
> java version "1.8.0_51"
> Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
> Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
> verapdf cfw$
> |
>
> The above is from my Mac mini test box and it has Java 8 
> installed and works with the latest version of the veraPDF 
> installer, GUI and CLI.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-190360865>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by edrobal** [comment] 2016-03-01 15:51
Hello.
I run the software and it display : some error in 
validating. But I know this and there is no report so it's 
not very useful.
Regards.

Le 29. 02. 16 21:07, Carl Wilson a écrit :
>
> Hi again, sorry for not responding sooner, we were putting 
> together the new release today, the installer is available 
> here 
> <http://downloads.verapdf.org/rel/verapdf-installer.zip>. 
> Could you give that a test and see whether your problem 
> persists. If so then please you give me a little more 
> information about your Java version and OS, e.g.
>
> |verapdf cfw$ java -version
> java version "1.8.0_51"
> Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
> Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
> verapdf cfw$
> |
>
> The above is from my Mac mini test box and it has Java 8 
> installed and works with the latest version of the veraPDF 
> installer, GUI and CLI.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-190360865>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by bdoubrov** [comment] 2016-03-01 15:57
This error message means the validator encountered a critical error and was not able to generate the report. Usually this is related to damaged PDF files.

If you could attach the PDF file in question, we would be able to provide more details.

**Comment by edrobal** [comment] 2016-03-01 18:56
I know that the pdf was not conform. This for this reason 
that I use your product. To see where is the error.
I attach the file.
Regards.

Le 01. 03. 16 16:57, Boris Doubrov a écrit :
>
> This error message means the validator encountered a 
> critical error and was not able to generate the report. 
> Usually this is related to damaged PDF files.
>
> If you could attach the PDF file in question, we would be 
> able to provide more details.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-190782603>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by carlwilson** [comment] 2016-03-02 09:39
Hi @edrobal , there doesn't seem to be an attachment and this is not the same issue as the JDK problem initially raised. Would you mind starting a new issue for the problem PDF and attaching the error information and the PDF itself please.

Many thanks,
Carl

**Comment by edrobal** [comment] 2016-03-02 10:55
OK I do this.

Regards

Le 02. 03. 16 10:39, Carl Wilson a écrit :
>
> Hi @edrobal <https://github.com/edrobal> , there doesn't 
> seem to be an attachment and this is not the same issue as 
> the JDK problem initially raised. Would you mind starting 
> a new issue for the problem PDF and attaching the error 
> information and the PDF itself please.
>
> Many thanks,
> Carl
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/veraPDF/veraPDF-library/issues/502#issuecomment-191156912>.
>

-- 

Christian Laborde

GTS - Informatique
Une division de GTS Gestion Tourisme Services Sàrl

+41 21 728 65 64

Sentier des Vinches
CH 1091 Grandvaux
Suisse

**Comment by carlwilson** [comment] 2016-03-04 15:47
Closing this as the original problem is solved.

**Closed by carlwilson** 2016-03-04 15:47 UTC
