### ISSUE TITLE
ToUnicode and U+0000, U+FEFF, U+FFFE

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#785] opened 2017-06-12 12:07 UTC
veraPDF 1.7.2 does not detect that this document:
[6.2.11.7.2-fail-1.pdf](https://github.com/veraPDF/veraPDF-library/files/1068036/6.2.11.7.2-fail-1.pdf)
violates clause 6.2.11.7.2 of ISO 19005-2:2011. Unfortunately, this error is quite common.

**Comment by a20god** [comment] 2017-06-12 12:33
Note that according to
http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/5411.ToUnicode.pdf

1 beginbfrange
<0000> <FFFF> ...whatever...
endbfrange

is invalid anyway as the first octet of the first code of the range and the first octet of the last code of the range must be identical. That is, to map all 65536 Codes, at least 256 ranges are needed.

**Comment by a20god** [comment] 2017-06-12 12:40
The ToUnicode CMap in my sample document maps 2-octet character codes to Unicode, whereas the font uses 1-octet character codes, which is also not detected by veraPDF.

**Comment by a20god** [comment] 2017-06-26 08:51
BTW, clause 6.2.11.7.2 of ISO 19005-2:2011 misses that U+FFFF, U+1FFFE, U+1FFFF, U+2FFFE, U+2FFFF, and so on are also noncharacter code points.

**Comment by bdoubrov** [comment] 2017-06-27 10:23
I agree that the construction:

```
1 beginbfrange
<0000> <FFFF> ...whatever...
endbfrange
```

is incorrect. I close this issue makring it as a duplicate of https://github.com/veraPDF/veraPDF-library/issues/778 .

**Closed by bdoubrov** 2017-06-27 10:23 UTC
