### ISSUE TITLE
Failed validation with embedded Type1 Fonts

### ISSUE THREAD

**Issue by jochen-unielektro** [veraPDF/veraPDF-library#1194] opened 2021-10-20 14:36 UTC
veraPDF reports the attached PDF/A-3B file as not compliant. However multiple validators including Adobe Preflight and 3-Heights accept the file.

[UNI ELEKTRO-ZUGFeRD.pdf](https://github.com/veraPDF/veraPDF-library/files/7381980/UNI.ELEKTRO-ZUGFeRD.pdf)
[xmlReport.txt](https://github.com/veraPDF/veraPDF-library/files/7381988/xmlReport.txt)

**Comment by bdoubrov** [comment] 2021-10-21 14:22
The issue is that the embedded font subsets have mismatch between the size of the CharStrings  dictionary and the real number of charstrings in the private part of the font(s). We now report this as a warning in stderr and continue processing the font and the PDF document.

**Comment by bdoubrov** [comment] 2022-01-24 11:26
Fix released in v1.20

**Closed by bdoubrov** 2022-01-24 11:26 UTC
Labels: fixed-in-dev
