### ISSUE TITLE
Validation issues, false positives?

### ISSUE THREAD

**Issue by mikael-s-andersson** [veraPDF/veraPDF-library#1038] opened 2019-09-02 14:25 UTC
Hi

We have a 3-Heights installation that we use to convert to PDF/A, specifically targetting PDF/A-2. For some files veraPDF would fail them due to various errors. Originally we thought it could be solved by upgrading 3H but that didn't do anything. 

At first we sent in a support ticket to the vendor of 3H but they more or less dismissed any responsibility on their end and claimed veraPDF was in the wrong. So after running the files through qpdf to be able to look at them manually it seems like they might have a point? Some files look like they might be incorrectly identified as invalid. Some however look like the vendor is being perhaps a bit hasty in dismissing veraPDF. However I don't know enough about how to read the files or the tests/source to really say one way or the other with any certainty. Not to mention not having access to the ISO spec, though it would most likely confuse me more than help at this point.

[2015-06-03_Artikel_HD.pdf](https://github.com/veraPDF/veraPDF-library/files/3566232/2015-06-03_Artikel_HD.pdf) - Failing 6.2.4.4 - This file looks like veraPDF is correct, there is literally not any Colorants tag in the file.

[FFU 2014-09-11_13.6 MUR_Strandpromenaden 5.pdf](https://github.com/veraPDF/veraPDF-library/files/3566241/FFU.2014-09-11_13.6.MUR_Strandpromenaden.5.pdf) - Failing 6.1.7 - Here I think veraPDF is correct, but I'm unsure.

[1283K-15840_doc.pdf](https://github.com/veraPDF/veraPDF-library/files/3566275/1283K-15840_doc.pdf) - Failing 6.1.8 - There are a few documents like this however where I am unsure if veraPDF is correct. The errors are all identical. Almost every time an error was triggered it was the swedish word "Brödtext".

[Begäran om offert.pdf](https://github.com/veraPDF/veraPDF-library/files/3566292/Begaran.om.offert.pdf) - Failing 6.7.4 & 6.1.8 - This one is I think is both correctly identified as invalid due to failing rule 6.7.4 but it is also failing a lot of rules due to the same reason as the file above.

[converted 4.12.txt](https://github.com/veraPDF/veraPDF-library/files/3566285/converted.4.12.txt) - Here's the complete report from veraPDF. It's an xml file but you can't attach those apparently so I changed the extension.

There are some other PDFs I didn't upload as you can see in the report, some didn't fail veraPDF but others I didn't upload since they were failing the same way as another document. If you want me to upload them tell me and I'll do so.

Best regards,
Mikael Andersson

**Comment by bdoubrov** [comment] 2019-09-04 11:01
Thanks a lot for reporting these issues. I can confirm that the failing 6.1.8 is indeed a veraPDF issue, while failing 6.1.7 is correct: several streams in the attached document (FFU 2014-09-11_13.6 MUR_Strandpromenaden 5.pdf) do spcify the compression as /A85, which is an abbreviation of /ASCII85Decode allowed only for inline images, but not in case of regular stream objects.

Failing 6.2.4.4 is related to one question that was recently raised and discussed at the Validation TWG of PDF Association. According to this discussion the document (2015-06-03_Artikel_HD.pdf) should be PDF/A compliant: the colorants of the DeviceN color space in this case are all process colorants. So, they don't require additional entries in the Colorants dictionary. We'll adjust the veraPDF implementation accordingly.

**Comment by mikael-s-andersson** [comment] 2019-09-05 07:52
Thanks for taking a look at my issue!

What about the file that failed 6.7.4 (Begäran om offert.pdf)? It seems like it simply fails the regex.

Best regards,
Mikael

**Comment by a20dev** [comment] 2019-10-27 19:10
Begaran.om.offert.pdf has a couple of PDF/A-2a violations that
are not reported by VeraPDF (because they are violations of
ISO 32000-1):

- Object 32 is an illustration element with Placement=Block. As such
  it must have a numeric Height attribute, but hasn't.

- That illustration element also has clipping operators outside a marked
  clipping sequence (EMC at offset 110 of stream 5).

- As usual, the ToUnicode streams are broken: they have a 16-bit code
  space but map 8-bit character codes.

2015-06-03_Artikel_HD.pdf only has broken ToUnicode streams which
assume that the code space is a range (rather than a rectangle).

1283K-15840_doc.pdf (like Begaran.om.offert.pdf) lacks numeric Height
and Width attributes for illustration elements with Placement Block
and Inline. It also has clipping operators outside a marked clipping
sequence for illustration elements.

In addition to A85 being used for image objects, there are some
embedded fonts in FFU.2014-09-11_13.6.MUR_Strandpromenaden.5.pdf with
a wrong value for Length1.

That is, none of the documents are conforming to PDF/A.

**Comment by bdoubrov** [comment] 2022-01-24 11:30
Fix released in v1.20

**Closed by bdoubrov** 2022-01-24 11:30 UTC
Labels: bug, P1, fixed-in-dev
