### ISSUE TITLE
PDF/A-4 validation failed for AP with text tag.

### ISSUE THREAD

**Issue by cybernetic10** [veraPDF/veraPDF-library#1266] opened 2022-07-11 14:19 UTC
[UntitledForm.pdf](https://github.com/veraPDF/veraPDF-library/files/9084739/pdfa_UntitledForm.pdf)
In attached sample there is failed validation for PDF/A-4 on listbox, which has appearance stream with command **/Tx BMC .... EMC**.
The failed rule says:
<html>
<body>

Specification: ISO 19005-4:2020, Clause: 6.2.2, Test number: 3 |  
-- | --
A content stream's named resources shall be defined by a resource dictionary, which shall enumerate the named resources needed by the operators in the content stream and the names by which they can be referred to.

</body>
</html>
I suppose this is error of veraPDF, because **/Tx** is not name of resource.

**Comment by MaximPlusov** [comment] 2022-07-11 14:39
This issue is duplicate of https://github.com/veraPDF/veraPDF-library/issues/1225 and already fixed in last development version [1.21.228](https://software.verapdf.org/develop/1.21)

**Closed** 2022-09-23 10:44 UTC
Labels: fixed-in-dev
