### ISSUE TITLE
Java heapspace errors

### ISSUE THREAD

**Issue by itzbund** [veraPDF/veraPDF-library#922] opened 2017-10-17 06:37 UTC
## Dev Effort
5D

## Description
Hi,

while parsing different bigger pdfs (> 200 Mb) the application throws a heap space error.
For some documents the work around with adding "set JAVA_OPTS=-Xmx1200m -XX:-UseGCOverheadLimit" into the .bat even with more memory works. But mostly the error is thrown.
What can i do?
By the way the performace with greenfield is much better.

Thanks!

**Comment by bdoubrov** [comment] 2017-10-17 08:35
Hi,

If possible, we'd interested to analyse any of these documents. We are constantly working on the improvements in performance and memory consumption. 

Other than that, the only suggestion would be to further increase the heap.

**Comment by bdoubrov** [comment] 2019-01-03 11:01
Duplicate of #905 . All further discussions will happen there

**Closed by bdoubrov** 2019-01-03 11:01 UTC
Labels: P1, feature
