### ISSUE TITLE
Issue with PDF/A-3A: 6.2.11.7

### ISSUE THREAD

**Issue by wroos** [veraPDF/veraPDF-library#812] opened 2017-06-22 13:20 UTC
The attached file is validated by several tools (e.g. callas pdf/a pillot, Acrobat, created with Adobe distiller as valid PDF/A-3A) to be compliant with PDF/A-3A. If validating the file with veraPDF 1.6.3 or veraPDF 1.4.1, veraPDF outputs that the file is not compliant with PDF/A-3A. The same counts if the file is checked with java integrated veraPDF-valdation release 1.4 or 1.6.

If the file is checked with veraPDF 1.0.8 (pdfbox) or veraPDF 1.2.1 (pdfbox) veraPDF outputs that the file is PDF/A-3A compliant. The same counts for using java integrated validation-model-pdfbox release 1.4.5.

It seems like the greenfield version of veraPDF has an issue with it.

Also attached you can find the html report (as pdf) of veraPDF1.6.3 validation.

[Example.pdf](https://github.com/veraPDF/veraPDF-library/files/1094860/Example.pdf)

[htmlReport.pdf](https://github.com/veraPDF/veraPDF-library/files/1094864/htmlReport.pdf)

**Comment by a20god** [comment] 2017-06-22 14:11
The ICCBased colour space in object 129 has an ICC profile stream that uses a CMYK device colour space as Alternate colour space, but the output intent uses an RGB colour space  (it's probably controversial whether this is a violation of ISO 19005-3:2012 as conforming readers shall ignore that Alternate colour space).

**Comment by bdoubrov** [comment] 2017-06-22 20:25
I believe this is indeed an issue of veraPDF's greenfield parser. Alternates of ICCBased color spaces should not be checked, as they are ignored by PDF/A comliant viewers. 

Otherwise there would be no way to use any ICCBased CMYK colors without a CMYK-based output intent.  

We'll fix this issue in one of the coming dev builds and in the next release.

**Comment by a20god** [comment] 2017-06-22 22:50
The "Alternate of ICCBased" problem is in my own PDF/A validator, so you don't have to fix anything there. (I don't think a PDF/A validator needs to be a conforming reader for PDF/A, but you have a point concerning CMYK ICCBased colour spaces.)

The problem veraPDF has with Example.pdf is related to ToUnicode. The condition

`toUnicode != null && toUnicode.indexOf("\u0000") == -1 && toUnicode.indexOf("\uFFFE") == -1 && toUnicode.indexOf("\uFEFF")  == -1`

looks wrong. The font in object 186 doesn't have a ToUnicode stream (and doesn't need one as the second condition of 6.2.11.7.2 is satisfied), therefore checking for U+0000 etc. should not be done. Perhaps this was intended:

`toUnicode == null || t(oUnicode.indexOf("\u0000") == -1 && toUnicode.indexOf("\uFFFE") == -1 && toUnicode.indexOf("\uFEFF")  == -1)`

**Comment by a20god** [comment] 2017-06-23 08:46
Correction: glyph name "a73" is not in the Adobe Glyph List (it's in the ITC Zapf Dingbats Glyph List), therefore ToUnicode is required. In consequence, the document does not conform to ISO 19005-3:2012.

**Comment by a20god** [comment] 2017-06-23 09:23
Another (controversial) problem with that document: Annotation dictionary (e.g.) 230 belongs to a checkbox field. Its AS entry is Off, but there is no appearance stream AP/N/Off which is to be used according to Table 164 of ISO 32000-1:2008 due to the value of AS. Note that this requirement contradicts 12.7.4.2.3 of ISO 3200-1:2008:

> The V entry in the field dictionary (see Table 220) holds a name object representing the check box’s appearance state, which shall be used to select the appropriate appearance from the appearance dictionary.

The latter requirement probably overrides the former as it is more specific (V for check box vs. AS for any annotation).
Let's assume that AS is to be used for the document under discussion as it lacks V.

6.3.3 of ISO 19005-3:2012 says:
> A conforming reader shall render the appearance dictionary without regard to any other keys and values in the annotation dictionary

That is, neither V nor AS shall select the appearance stream, which contradicts ISO 32000-1:2008. Which appearance stream is a conforming reader to use if there is more than one? There clearly is something wrong with ISO 19005.

Back to the document: Note 1 in 6.3.3 of ISO 19005-3:2012 says:

> Requiring an appearance dictionary for each annotation ensures the reliable rendering of the annotations.

That is, not having an appearance stream for the currently active button state is against the spirit (if not the words) of that note. See also 6.4.1:

> The intent of the requirements of 6.4 is to ensure that there is no ambiguity about the rendering of form
fields.

BTW, 6.3.3 of ISO 19005-2:2012 also says:

> If an annotation dictionary’s Subtype key has a value of Widget and its FT key has a value
of Btn

That's probably yet another misprint as FT is not defined for annotation dictionaries, there can be be only an FT entry if a field dictionary is merged with its annotation dictionary. The wording does not cover the case of a field dictionary having two or more annotations in its Kids array.

What a mess.

**Comment by wroos** [comment] 2017-06-27 08:36
thanks for dealing with Example.pdf.

**Comment by shem-sergey** [comment] 2017-06-28 14:17
Problem with toUnicode mapping was fixed. Indeed veraPDF had some inconsistencies with determining toUnicode value for some categories of fonts.

**Comment by bdoubrov** [comment] 2019-01-03 11:42
Fixed in veraPDF 1.12

**Closed by bdoubrov** 2019-01-03 11:42 UTC
Labels: in progress
