### ISSUE TITLE
Empty CIDSet stream

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-library#833] opened 2017-07-05 10:14 UTC
veraPDF 1.7.51 behaves differently for these documents which both have an empty CIDSet stream (it should not be empty due to 6.2.11.4 of ISO 19005-2:2011):

[CIDSet-5.pdf](https://github.com/veraPDF/veraPDF-library/files/1124283/CIDSet-5.pdf)
[CIDSet-4.pdf](https://github.com/veraPDF/veraPDF-library/files/1124282/CIDSet-4.pdf)

The difference between those documents is the Filter used for the CIDSet stream.

**Comment by a20god** [comment] 2017-07-05 10:15
I guess that for one of the two documents, veraPDF thinks that the CIDSet stream is not present. So, this may also affect the check for presence of CIDSet for PDF/A-1.

**Comment by bdoubrov** [comment] 2020-07-30 12:46
The latest version of veraPDF (1.16) still regards these CIDSets as valid. Looks like this is a duplicate of https://github.com/veraPDF/veraPDF-library/issues/811

**Comment by bdoubrov** [comment] 2021-05-24 10:10
veraPDF does not check CIDSet entries in this case, as the CIDSet font name does not have a subset prefix. See #811 for more explanation

**Closed by bdoubrov** 2021-05-24 10:10 UTC
