### ISSUE TITLE
Differnet Result for GreenField- and PDFBox-Implementation

### ISSUE THREAD

**Issue by r-pf** [veraPDF/veraPDF-library#938] opened 2018-02-02 16:31 UTC
For the file
[HelloWorld.pdf](https://github.com/veraPDF/veraPDF-library/files/1689996/HelloWorld.pdf)
the Greenfield-implementations 1.10.5 and 1.11.1 reports an error - means the file is invalid - whereas the PDFBox-implementations  1.10.2 and 1.11.1 reports that the PDF-File is valid.

Is there an implementations which should be preferred - Greenfield or PDFBox?

**Comment by bdoubrov** [comment] 2018-02-04 18:30
The result of Greenfield is correct -- CIDSet of the embedded font does not list all glyphs are required. 
We'll check why PDFBox version does not report this error. 

In general, we recommend using Greenfield implementation starting from version 1.0. This is where most of our further development will done. But we are trying to ensure at the same time that the validation results are identical for both version. So, your file is clearly a bug in PDFBox implementation, and we'll have a look at it.

**Comment by bdoubrov** [comment] 2019-01-03 10:45
Duplicate of #983. Will be fixed along with the new implementation of the CIDSet / CharSet validation logic.

**Closed by bdoubrov** 2019-01-03 10:45 UTC
Labels: duplicate
